export const DASHBOARD_METRICS_REQUEST = 'DASHBOARD_METRICS_REQUEST';
export const DASHBOARD_METRICS_SUCCESS = 'DASHBOARD_METRICS_SUCCESS';
export const DASHBOARD_METRICS_FAILURE = 'DASHBOARD_METRICS_FAILURE';
